config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Be careful about route placement, and restart server when adding routes
  root 'welcome#index'

  resources :participants
  resources :game_library
  get '/game_library/list_game/:id', to: 'game_library#gameinfo'
  get '/game_library/list_member/:badge', to: 'game_library#memberinfo'
  resources :game_logs
  get 'check_entry/:badge_id', to: 'game_logs#need_reg'
  resources :winner_circle
  get 'show_winners', to: 'winner_circle#show_winners'
  get 'redraw', to: 'winner_circle#redraw_winner'
  resources :inventories
  resources :events
  resources :schedules
  resources :rules
  resources :paw_staffs, path: 'staff'
  resources :con_staffs
  resources :users

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/schedule.rb
# frozen_string_literal: true

#:nodoc:
class Schedule < ApplicationRecord
  validates :inventory_id, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :event_id, presence: true
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

#:nodoc:
class SchedulesController < ApplicationController
  skip_before_action :admin, only: [:index]

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)

    if @schedule.save
      flash[:notice] = 'Scheduled game has been added.'
      redirect_to schedules_path
    else
      flash[:alert] = 'Something went wrong.'
      render 'new'
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
    @title = Inventory.find(params[:inventory_id])
    @staff = PawStaff.find(params[:paw_staff_id]) unless params[:paw_staff_id].nil?
    @scheduled_event = Event.find(params[:event_id])
  end

  def update
    @schedule = Schedule.find(params[:id])

    if @schedule.update_attributes(schedule_params)
      flash[:notice] = 'Scheduled game has been updated.'
      redirect_to schedules_path
    else
      flash[:alert] = 'Unable to save edit.'
      render 'edit'
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id]).destroy
    flash[:notice] = 'Scheduled game has been deleted.'
    redirect_to schedules_path
  end

  def index
    @schedule = Schedule.all.order(:inventory_id)
    @schedule_info = []
    @schedule_details = []

    @schedule.length.times do |i|
      @schedule_info[i] = if !@schedule[i][:paw_staff_id].nil?
                            {
                              id: @schedule[i][:id],
                              inventory_id: @schedule[i][:inventory_id],
                              paw_staff_id: @schedule[i][:participant_id],
                              title: Inventory.find(@schedule[i][:inventory_id])[:title],
                              staff_member: PawStaff.find(@schedule[i][:paw_staff_id])[:name],
                              start: @schedule[i][:start],
                              end: @schedule[i][:end],
                              location: @schedule[i][:location],
                              event_id: @schedule[i][:event_id]
                            }
                          else
                            {
                              id: @schedule[i][:id],
                              inventory_id: @schedule[i][:inventory_id],
                              paw_staff_id: @schedule[i][:participant_id],
                              title: Inventory.find(@schedule[i][:inventory_id])[:title],
                              staff_member: 'Pending',
                              start: @schedule[i][:start],
                              end: @schedule[i][:end],
                              location: @schedule[i][:location],
                              event_id: @schedule[i][:event_id]
                            }
                          end
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:inventory_id,
                                     :location,
                                     :paw_staff_id,
                                     :start,
                                     :end,
                                     :event_id)
  end
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

#:nodoc:
module SchedulesHelper
end

app/views/schedules/_schedule_form.html.erb
    <table>
      <%= form_with(model: @schedule) do |f| %>
        <tr>
          <th><%= f.label :inventory_id %></th>
          <td><%= f.collection_select :inventory_id, Inventory.all, :id, :game_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr>
          <th><%= f.label :start %></th>
          <td><%= f.datetime_local_field :start, required: true %></td>
        </tr>
        <tr>
          <th><%= f.label :end %></th>
          <td><%= f.datetime_local_field :end %></td>
        </tr>
        <tr>
          <th><%= f.label :paw_staff_id %></th>
          <td><%= f.collection_select :paw_staff_id, PawStaff.all, :id, :staff_name, include_blank: true, selected: 0 %></td>
        </tr>
        <tr>
          <th><%= f.label :location %></th>
          <td><%= f.text_field :location %></td>
        </tr>
        <tr>
          <th><%= f.label :event_id %></th>
          <td><%= f.collection_select :event_id, Event.all, :id, :event_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr><td colspan="3"><%= f.submit %></td></tr>
        <% end %>
    </table>

app/views/schedules/edit.html.erb
<article class="sing-col-sm">
    <table>
      <tr>
        <th></th>
        <th>Original</th>
        <th>Edit</th>
      </tr>
      <%= form_with(model: @schedule) do |f| %>
        <tr>
          <th><%= f.label :inventory_id %></th>
          <td><%= @title[:title] %></td>
          <td><%= f.collection_select :inventory_id, Inventory.all, :id, :game_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr>
          <th><%= f.label :start %></th>
          <td class="timestamp"><%= @schedule[:start] %></td>
          <td><%= f.datetime_local_field :start, required: true %></td>
        </tr>
        <tr>
          <th><%= f.label :end %></th>
          <td class="timestamp"><%= @schedule[:end] %></td>
          <td><%= f.datetime_local_field :end %></td>
        </tr>
        <tr>
          <th><%= f.label :paw_staff_id %></th>
          <td>
            <% unless @staff.nil? %>
              <%= @staff[:name] %>
            <% else %>
              NA
            <% end %>
            </td>
          <td><%= f.collection_select :paw_staff_id, PawStaff.all, :id, :staff_name, include_blank: true, selected: 0 %></td>
        </tr>
        <tr>
          <th><%= f.label :location %></th>
          <td><%= @schedule[:location] %></td>
          <td><%= f.text_field :location %></td>
        </tr>
        <tr>
          <th><%= f.label :event_id %></th>
          <td><%= @scheduled_event[:event_code] %></td>
          <td><%= f.collection_select :event_id, Event.all, :id, :event_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr><td colspan="3"><%= f.submit %></td></tr>
      <% end %>
    </table>
</article>

app/views/schedules/index.html.erb
<article class="sing-col-sm">
    <table>
      <tr>
        <th>Title</th>
        <th>GM</th>
        <th>Location</th>
        <th>Start Time</th>
        <th>End Time</th>
        <% if session[:user_name] == "admin" %>
          <th>Admin Controls</th>
        <% end %>
      </tr>
      <% @schedule_info.each do |s| %>
        <tr>
          <td class="title"><%= s[:title] %></td>
          <td><%= s[:staff_member] %></td>
          <td><%= s[:location] %></td>
          <td class="timestamp"><%= s[:start] %></td>
          <td class="timestamp"><%= s[:end] %></td>
          <% if session[:user_name] == "admin" %>
            <td>
              <%= link_to "Edit", edit_schedule_path(s), method: :get %>
              <%= link_to 'Delete', schedule_path(s), method: :delete, data: { confirm: "Are you sure?" } %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <br><br>
    <% if session[:user_name] == "admin" %>
      <%= button_to "Add to Schedule", new_schedule_path, method: :get %>
    <% end %>
</article>

app/views/schedules/new.html.erb
<article class="sing-col-sm">
  <%= render 'schedule_form' %>
</article>