config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Be careful about route placement, and restart server when adding routes
  root 'welcome#index'

  resources :participants
  resources :game_library
  get '/game_library/list_game/:id', to: 'game_library#gameinfo'
  get '/game_library/list_member/:badge', to: 'game_library#memberinfo'
  resources :game_logs
  get 'check_entry/:badge_id', to: 'game_logs#need_reg'
  resources :winner_circle
  get 'show_winners', to: 'winner_circle#show_winners'
  get 'redraw', to: 'winner_circle#redraw_winner'
  resources :inventories
  resources :events
  resources :schedules
  resources :rules
  resources :paw_staffs, path: 'staff'
  resources :con_staffs
  resources :users

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/active_log.rb
# frozen_string_literal: true

#:nodoc:
class ActiveLog < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

#:nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def admin?
    session[:user_name] == 'admin'
  end
end

app/models/con_staff.rb
# frozen_string_literal: true

#:nodoc:
class ConStaff < ApplicationRecord
  validates :name, presence: true
  validates :event_id, presence: true

  def self.con_list
    @con_staffs = ConStaff.all
    @con_info = []

    @con_staffs.length.times do |i|
      @con_info[i] = {
        id: @con_staffs[i][:id],
        name: @con_staffs[i][:name],
        title: @con_staffs[i][:title],
        phone: @con_staffs[i][:phone],
        email: @con_staffs[i][:email],
        event_id: @con_staffs[i][:event_id],
        event_code: Event.find(@con_staffs[i][:event_id])[:event_code]
      }
    end
    @con_info
  end
end

app/models/event.rb
# frozen_string_literal: true

#:nodoc:
class Event < ApplicationRecord
  validates :event_code, presence: true

  def event_selection
    event_code.to_s
  end
end

app/models/game_log.rb
# frozen_string_literal: true

#:nodoc:
class GameLog < ApplicationRecord
  validates :inventory_id, presence: true
  validates :timestamp, presence: true
  validates :event_id, presence: true
  validates :participant_id, presence: true
  serialize :entry, JSON

  def self.log_info(logs)
    @log_info = []
    if logs.class != GameLog
      logs.length.times do |i|
        @log_info[i] = { id: logs[i][:id],
                         inventory_id: logs[i][:inventory_id],
                         title: Inventory.find(logs[i][:inventory_id])[:title],
                         timestamp: logs[i][:timestamp],
                         participant_id: logs[i][:participant_id],
                         member: Participant.find(logs[i][:participant_id])[:name],
                         rating: logs[i][:rating] }
      end
    else
      @log_info = { id: logs[:id],
                    inventory_id: logs[:inventory_id],
                    title: Inventory.find(logs[:inventory_id])[:title],
                    timestamp: logs[:timestamp],
                    participant_id: logs[:participant_id],
                    member: Participant.find(logs[:participant_id])[:name],
                    rating: logs[:rating] }
    end
    @log_info
  end

  def self.update_record(update_id)
    GameLog.find(update_id)
  end

  def self.destroy_record(destroy_id)
    GameLog.find(destroy_id).destroy
  end
end

app/models/inventory.rb
# frozen_string_literal: true

#:nodoc:
class Inventory < ApplicationRecord
  has_many :game_logs
  has_many :libraries
  has_many :schedules

  validates :title, presence: true

  def game_selection
    title.to_s
  end
end

app/models/library.rb
# frozen_string_literal: true

#:nodoc:
class Library < ApplicationRecord
  # Update table so that there is a static one-to-one relationship between inventory quantity and initial quantity in the library?

  validates :inventory_id, presence: true
  validates :participant_id, presence: true

  def self.games_out
    @history = {}
    @library = Library.all.order(checked_out: :desc)
    t = 0
    @library.each do |log|
      next unless log.checked_out

      @history[t] = { time: log.checked_out,
                      quantity: log.quantity_left,
                      name: Participant.find(log.participant_id).name,
                      badge: Participant.find(log.participant_id).badge,
                      game: Inventory.find(log.inventory_id).title }
      t += 1
    end
    @history
  end
end

app/models/participant.rb
# frozen_string_literal: true

#:nodoc:
class Participant < ApplicationRecord
  validates :badge, presence: true, uniqueness: true
  validates :name, presence: true

  def badge_selection
    badge.to_s
  end
end

app/models/paw_staff.rb
# frozen_string_literal: true

#:nodoc:
class PawStaff < ApplicationRecord
  validates :name, presence: true

  def staff_name
    "#{name} -- Badge: #{badge}"
  end

  def self.simplify(staff)
    all_info = PawStaff.find(staff)
    simple_info = { ID: all_info[:id],
                    Badge: all_info[:badge],
                    Name: all_info[:name],
                    Title: all_info[:title],
                    Phone: all_info[:phone],
                    Email: all_info[:email],
                    Role: all_info[:role] }
  end
end

app/models/schedule.rb
# frozen_string_literal: true

#:nodoc:
class Schedule < ApplicationRecord
  validates :inventory_id, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :event_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

#:nodoc:
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_secure_password

  def self.find_user(name)
    user = User.find_by(username: name)
    user
  end
end

app/helpers/con_staffs_helper.rb
# frozen_string_literal: true

#:nodoc:
module ConStaffsHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

#:nodoc:
module EventsHelper
end

app/helpers/game_logs_helper.rb
# frozen_string_literal: true

#:nodoc:
module GameLogsHelper
end

app/helpers/paw_staffs_helper.rb
# frozen_string_literal: true

#:nodoc:
module PawStaffsHelper
end

app/helpers/rules_helper.rb
# frozen_string_literal: true

#:nodoc:
module RulesHelper
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

#:nodoc:
module SchedulesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

#:nodoc:
module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

#:nodoc:
module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

#:nodoc:
module WelcomeHelper
end

app/views/shared/_addmember.html.erb
<script>

  $(document).ready(function(){
    $("input[type=radio]").change(function (e) {
      $("#true, #false").removeClass("selected");
      $("#" + $(e.currentTarget).val()).addClass("selected");
    });
  });

</script>
<section>
<%= form_with url: participants_path, model: @participant, id: "member_submit" do |form| %>
  <div class="member_info">Badge: <%= form.number_field "member[badge]", {required: true} %></div><br>
  <div class="member_info">Name: <%= form.text_field "member[name]", {required: true} %></div><br>
  <div class="member_info">Phone: <%= form.telephone_field "member[phone]" %></div><br>
  <div class="member_info">Email: <%= form.text_field "member[email]" %></div><br>
  <div class="member_info">Preference: <%= form.select "member[pref]", ["Text", "Call", "Email"] %></div><br>
  <div class="member_info">Proxy Info: Yes<%= form.radio_button "member[proxy]", :true %>
  No<%= form.radio_button "member[proxy]", :false %></div>

  <div id="false"></div>
  <div id="true" class="member_info">
    Enter Proxy's Information<br><br>
    Badge: <%= form.number_field "member[p_badge]" %><br><br>
    Name: <%= form.text_field "member[p_name]" %><br><br>
    Phone: <%= form.number_field "member[p_phone]" %><br><br>
    Email: <%= form.text_field "member[p_email]" %><br><br>
    Preference: <%= form.select "member[p_pref]", ["Call","Text","Email"] %>
  </div>


<% end %>
</section>

app/views/shared/_header.html.erb
<header class="header" id="main_header">
  <%= link_to image_tag("PAW-Logo.jpg", id: "menu_img", alt: "PAW Logo"), root_path, id: "img_link" %>
  <div id="program">
    Play and Win
  </div>
  <nav id="pages">
    <%= link_to "Add Participant", new_participant_path %>
    <%= link_to "Add Game Log", new_game_log_path %>
    <%= link_to "Library", new_game_library_path %>
  </nav>
  <nav id="default">
    <ul class="top-level-menu">
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <% if session[:user_id] != nil %>
        <%= link_to "Logout", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Login", login_path %>
      <% end %>
    </li>
    <li>
      <a href="#">Admin</a>
      <ul class="second-level-menu">
        <li>
          <a href="#">Staff</a>
          <ul class="third-level-menu">
            <li><%= link_to "PAW Staff", paw_staffs_path %></li>
            <li><%= link_to "Con Staff", con_staffs_path %></li>
          </ul>
        </li>
        <li><%= link_to "Inventory", inventories_path %></li>
        <li><%= link_to "Event Schedule", schedules_path %></li>
        <li><%= link_to "Game Logs", game_logs_path %></li>
        <li><%= link_to "Participants", participants_path %></li>
        <% if session[:user_name] == 'admin' %>
          <li><%= link_to "Library Logs", game_library_index_path %></li>
          <li><%= link_to "Event Information", events_path %></li>
          <li><%= link_to "Winner Circle", winner_circle_index_path %></li>
        <% end %>
      </ul>
    </li>
    </ul>
  </nav>
  <div id="event_code">
    Event: <%= @event_info[0]["event_code"] %>
  </div>
  <div id="user_info">
    <% if session[:user_id] != nil %>
      <%= "User: #{session[:user_name]}" %>
    <% else %>
      <%= "You are not currently logged in." %>
    <% end %>
  </div>
</header>