config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Be careful about route placement, and restart server when adding routes
  root 'welcome#index'

  resources :participants
  resources :game_library
  get '/game_library/list_game/:id', to: 'game_library#gameinfo'
  get '/game_library/list_member/:badge', to: 'game_library#memberinfo'
  resources :game_logs
  get 'check_entry/:badge_id', to: 'game_logs#need_reg'
  resources :winner_circle
  get 'show_winners', to: 'winner_circle#show_winners'
  get 'redraw', to: 'winner_circle#redraw_winner'
  resources :inventories
  resources :events
  resources :schedules
  resources :rules
  resources :paw_staffs, path: 'staff'
  resources :con_staffs
  resources :users

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/con_staff.rb
# frozen_string_literal: true

#:nodoc:
class ConStaff < ApplicationRecord
  validates :name, presence: true
  validates :event_id, presence: true

  def self.con_list
    @con_staffs = ConStaff.all
    @con_info = []

    @con_staffs.length.times do |i|
      @con_info[i] = {
        id: @con_staffs[i][:id],
        name: @con_staffs[i][:name],
        title: @con_staffs[i][:title],
        phone: @con_staffs[i][:phone],
        email: @con_staffs[i][:email],
        event_id: @con_staffs[i][:event_id],
        event_code: Event.find(@con_staffs[i][:event_id])[:event_code]
      }
    end
    @con_info
  end
end

app/controllers/con_staffs_controller.rb
# frozen_string_literal: true

#:nodoc:
class ConStaffsController < ApplicationController
  skip_before_action :admin, only: [:index]
  before_action :set_con_staff, only: %i[show edit update destroy]

  # GET /con_staffs
  # GET /con_staffs.json
  def index
    @con_info = ConStaff.con_list
  end

  # GET /con_staffs/new
  def new
    @con_staff = ConStaff.new
  end

  # POST /con_staffs
  # POST /con_staffs.json
  def create
    @con_staff = ConStaff.new(con_staff_params)

    respond_to do |format|
      if @con_staff.save
        format.html do
          redirect_to con_staffs_path,
                      notice: 'Con staff was successfully created.'
        end
        format.json do
          render :show,
                 status: :created,
                 location: @con_staff
        end
      else
        puts @con_staff.errors.full_messages
        format.html { render :new }
        format.json do
          render json: @con_staff.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /con_staffs/1
  # PATCH/PUT /con_staffs/1.json
  def update
    respond_to do |format|
      if @con_staff.update(con_staff_params)
        format.html do
          redirect_to con_staffs_path,
                      notice: 'Con staff was successfully updated.'
        end
        format.json do
          render :show,
                 status: :ok, location: @con_staff
        end
      else
        format.html { render :edit }
        format.json do
          render json: @con_staff.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /con_staffs/1
  # DELETE /con_staffs/1.json
  def destroy
    ConStaff.find(params[:id]).destroy
    flash[:notice] = 'Con staff has been deleted.'
    redirect_to con_staffs_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_con_staff
    @con_staff = ConStaff.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def con_staff_params
    params.require(:con_staff).permit(:name,
                                      :title,
                                      :phone,
                                      :email,
                                      :event_id)
  end
end

app/helpers/con_staffs_helper.rb
# frozen_string_literal: true

#:nodoc:
module ConStaffsHelper
end

app/views/con_staffs/_form.html.erb
<%= form_with(model: con_staff, local: true) do |form| %>
  <% if con_staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(con_staff.errors.count, "error") %> prohibited this con_staff from being saved:</h2>

      <ul>
      <% con_staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select :event_id, Event.all, :id, :event_selection, {prompt: true}, {required: true} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/con_staffs/edit.html.erb
<article class="sing-col-sm">
  <h1>Editing Con Staff</h1>
    <table>
      <tr>
        <th></th>
        <th>Original</th>
        <th>Edit</th>
      </tr>
      <%= form_with(model: @con_staff) do |f| %>
        <tr>
          <th><%= f.label :name %></th>
          <td><%= @con_staff[:name] %></td>
          <td><%= f.text_field :name, required: true %></td>
        </tr>
        <tr>
          <th><%= f.label :title %></th>
          <td><%= @con_staff[:title] %></td>
          <td><%= f.text_field :title %></td>
        </tr>
        <tr>
          <th><%= f.label :phone %></th>
          <td><%= @con_staff[:phone] %></td>
          <td><%= f.phone_field :phone %></td>
        </tr>
        <tr>
          <th><%= f.label :email %></th>
          <td><%= @con_staff[:email] %></td>
          <td><%= f.email_field :email %></td>
        </tr>
        <tr>
          <th><%= f.label :event_id %></th>
          <td><%= @con_staff[:event_id] %></td>
          <td><%= f.collection_select :event_id, Event.all, :id, :event_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr><td colspan="3"><%= f.submit %></td></tr>
      <% end %>
    </table>

    <%= link_to 'Back', con_staffs_path %>
</article>

app/views/con_staffs/index.html.erb
  <article class="sing-col-sm">
    <h3>Convention Staff</h3>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Event</th>
          <% if session[:user_name] == "admin" %>
          <th></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @con_info.each do |con_staff| %>
          <tr>
            <td><%= con_staff[:name] %></td>
            <td><%= con_staff[:title] %></td>
            <td><%= con_staff[:phone] %></td>
            <td><%= con_staff[:email] %></td>
            <td><%= con_staff[:event_code] %></td>
            <% if session[:user_name] == "admin" %>
            <td>
              <%= link_to 'Edit', edit_con_staff_path(con_staff) %>
              <%= link_to 'Delete', con_staff_path(con_staff), method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <% if session[:user_name] == "admin" %>
      <%= button_to 'New Con Staff', new_con_staff_path, method: :get %>
    <% end %>
  </article>

app/views/con_staffs/new.html.erb
<article class="sing-col-sm">
    <h1>New Con Staff</h1>
    <table>
      <%= form_with(model: @con_staff) do |f| %>
        <tr>
          <th><%= f.label :name %></th>
          <td><%= f.text_field :name, required: true %></td>
        </tr>
        <tr>
          <th><%= f.label :title %></th>
          <td><%= f.text_field :title %></td>
        </tr>
        <tr>
          <th><%= f.label :badge %></th>
          <td><%= f.number_field :badge %></td>
        </tr>
        <tr>
          <th><%= f.label :phone %></th>
          <td><%= f.phone_field :phone %></td>
        </tr>
        <tr>
          <th><%= f.label :email %></th>
          <td><%= f.email_field :email %></td>
        </tr>
        <tr>
          <th><%= f.label :event_id %></th>
          <td><%= f.collection_select :event_id, Event.all, :id, :event_selection, {prompt: true}, {required: true} %></td>
        </tr>
        <tr><td colspan="2"><%= f.submit %></td></tr>
      <% end %>
    </table>

    <%= link_to 'Back', con_staffs_path %>
  </div>
</article>

app/views/con_staffs/show.html.erb
<div class="con-container">
  <div id="con_form">
    <p>
      <strong>Name:</strong>
      <%= @con_staff.name %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @con_staff.title %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @con_staff.phone %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @con_staff.email %>
    </p>

    <p>
      <strong>Event:</strong>
      <%= @con_staff.event_id %>
    </p>

    <%= link_to 'Edit', edit_con_staff_path(@con_staff) %> |
    <%= link_to 'Back', con_staffs_path %>
  </div>
</div>